### PR TITLE
Create an ad-hoc shell environment for ease of use. 

### PR DESCRIPTION
**Pull request by lewalkingdad**
Leveraging `nix flake` and `direnv` to automatically setup the project environment.

it will download automatically (given you have `direnv` installed and allowed the folder, other wise you will have to type `nix develop` to get into the environment.) `F#`, `.NET SDK 8.0`, `NodeJS` & `PNPM` so you can start right away, without the need to install those dependencies system wide.

A possible next step could be to let nix build the project (i.e `nix build` && `nix run`) (for generating release/production version).

### CODE REVIEW

**Comment by laurentpayot** [comment]
Hi Damien, thank you for your interest in this repository and for your PR.

I have zero knowledge of Nix and less than zero knowledge of Nix flakes. I cannot merge your PR _right now_ because I have first to understand what it does :sweat_smile:
After a quick search it seems that Nix Flakes are an experimental and somewhat [controversial](https://discourse.nixos.org/t/experimental-does-not-mean-unstable-detsyss-perspective-on-nix-flakes/32703/2) feature. Maybe waiting for a broader adoption would be a good idea? This repository is a minimalist example and should be as less opinionated as possible. 
I’ve added a link to this PR changed files in the README file so people interested in Nix flakes can find it easily.

**Comment by lewalkingdad** [comment]
Very fair point, I've been so mind blown by flakes that I forgot their experimental status. Also I discovered that not everyone was on board with it so Kudos for that :)

I could provide a `shell.nix` too (using `nix-shell` which is a stable feature) if you are okay with it.


Anyway, I wanted to thank you for this repository, it allowed me to have a quick play with F#, I'm not totally fond of it, but I'm not despising it so  I count it as a win. :P

**Comment by laurentpayot** [comment]
Thanks Damien. Yes F# is a bit special as it is functional but not pure.

I really appreciate and I wish I could say yes to your `shell.nix` proposal but the goal of this repository is to provide a _minimalist_ example. Adding this file would make people think it is something  mandatory, or even think this example can only run on Nix OS.

**Comment by laurentpayot** [comment]
Closing PR as not up to date to latest changes.

**Pull request closed without merging**
